// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kirpolypoknwkvzlcjki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpcnBvbHlwb2tud2t2emxjamtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODgxNTcsImV4cCI6MjA3Mzk2NDE1N30.2vreGvREOaAiRtLJOhXi7gJ-VNDc1x0AXtx_-jLrqXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});