// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqhbdehagfntbccamshz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxaGJkZWhhZ2ZudGJjY2Ftc2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODY5OTQsImV4cCI6MjA3Mzk2Mjk5NH0.xTB92qq-g9_bFcFk_zKscugeBYR8QkaKG0Kr_qGRCAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});